### ISSUE TITLE
Using Imaging Source Camera (IC4) for experiments with Python

### ISSUE THREAD

**Issue by KalpitBakal** [TheImagingSource/ic4-examples#25]
Hello! 
I have been using Imaging Source camera with IC Capture for my microscopy experiments for a while now. However, now I want to automate a few things and save the new API of IC4 in **Python**. I will explain a few things what I want to achieve. It would be great if you could nudge me in the right directions with the examples and the documentation. I have a basic knowledge in Python. So here it goes, 

1. I want to use the Imaging Source camera to display the live video in a window. I know I could use cv2 to show the webcam of my laptop live. What function/class should I look into to display the live video of the Imaging Source Camera on window. 

2. In addition to point 2, I want to save this live video into a folder just as I can do in the IC Capture application. I would like to set the format, fps etc

3. In addition to point 2 and 3, I would like to snap an image after a set time and save it to a particular folder. Is it possible to use time.sleep() and not disrupt the live video display and saving? Because I know this is a problem when I want to use it with cv2 and the webcam. 

If doing all this 3 steps in one python function is not possible, please let me know that too. This is a general description of my project but if you want more details I will give more explanation happily.

**Comment by TIS-Tim** [comment]
The qt6-first-steps example shows how to display live video: https://github.com/TheImagingSource/ic4-examples/tree/master/python/qt6/qt6-first-steps

The demoapp example expands on this to manually allow saving single images and video files: https://github.com/TheImagingSource/ic4-examples/tree/master/python/qt6/demoapp

The documentation contains a section explaining how to programmatically configure camera parameters like resolution and exposure time: https://www.theimagingsource.com/en-us/documentation/ic4python/guide-configuring-device.html (frame rate is not shown there, but setting ic4.PropId.ACQUISITION_FRAME_RATE will do the trick.

The easiest way to build some regular/timed image capture is probably to extend one of the Qt examples with a Qt timer. sleep will block the UI thread and make the program unresponsive.

**Comment by KalpitBakal** [comment]
Hello Tim, 

Thank you for your quick response. I will look into these examples. 

_The easiest way to build some regular/timed image capture is probably to extend one of the Qt examples with a Qt timer. sleep will block the UI thread and make the program unresponsive._

**Will this stop showing the live video and stop saving the video in the folder as well?**

**Comment by TIS-Tim** [comment]
Yes, rendering using ic4.pyside6.DisplayWidget requires main thread interaction. If you do time.sleep on the main thread, live display will halt.

**Comment by TIS-Tim** [comment]
No, just set up a timer: https://doc.qt.io/qtforpython-6/PySide6/QtCore/QTimer.html

In the connected callback, do what you want to do after the time has elapsed, like capture the next image. No need to create threads.

**Comment by TIS-Tim** [comment]
No, that will just register a function to be called later. The program continues on doing whatever it does.

**Comment by KalpitBakal** [comment]
On a side note, if we use the Imaging Source Camera as a webcam, will there a problem like jumping frames amongst many others? Or you think it will work smoothly?

**Comment by TIS-Tim** [comment]
What do you mean by "use as a webcam"?

Please direct questions unrelated to ic4 to our normal support channel: https://www.theimagingsource.com/en-de/company/contact/

**Comment by Skullface9512** [comment]
Hi, i want to know how to set white balance auto as off in python

**Comment by TIS-Tim** [comment]
The [Documentation](https://www.theimagingsource.com/en-us/documentation/ic4python/guide-configuring-device.html) explains in detail how to configure device settings.

The constant for auto white balance is `ic4.PropId.BALANCE_WHITE_AUTO`. To disable auto white balance, set it to `"Off"`.

**Comment by Skullface9512** [comment]
Rencently i come across some problems, i want to take photos from two devices at the same time, the method i tried is:
```ic4.Library.init()
grabber = ic4.Grabber()
grabber1 = ic4.Grabber()
first_device_info = ic4.DeviceEnum.devices()[0]
second_device_info = ic4.DeviceEnum.devices()[1]
grabber.device_open(first_device_info)
grabber1.device_open(second_device_info)

grabber.device_property_map.set_value(ic4.PropId.EXPOSURE_AUTO, "Off")
grabber1.device_property_map.set_value(ic4.PropId.EXPOSURE_AUTO, "Off")
grabber.device_property_map.set_value(ic4.PropId.EXPOSURE_TIME, 55555)
grabber1.device_property_map.set_value(ic4.PropId.EXPOSURE_TIME, 55555)
grabber.device_property_map.set_value(ic4.PropId.GAIN_AUTO, "Off")
grabber1.device_property_map.set_value(ic4.PropId.GAIN_AUTO, "Off")
grabber.device_property_map.set_value(ic4.PropId.GAIN, 3)
grabber1.device_property_map.set_value(ic4.PropId.GAIN, 3)
grabber.device_property_map.set_value(ic4.PropId.BALANCE_WHITE_AUTO,"Off")
grabber1.device_property_map.set_value(ic4.PropId.BALANCE_WHITE_AUTO,"Off")
grabber.device_property_map.set_value(ic4.PropId.ACQUISITION_FRAME_RATE,1.5)
grabber1.device_property_map.set_value(ic4.PropId.ACQUISITION_FRAME_RATE,1.5)
grabber.device_property_map.set_value(ic4.PropId.WIDTH, 3072)
grabber1.device_property_map.set_value(ic4.PropId.WIDTH, 3072)
grabber.device_property_map.set_value(ic4.PropId.HEIGHT, 2048)
grabber1.device_property_map.set_value(ic4.PropId.HEIGHT, 2048)

sink = ic4.SnapSink()
sink1 = ic4.SnapSink()
grabber.stream_setup(sink, setup_option=ic4.StreamSetupOption.ACQUISITION_START)
grabber1.stream_setup(sink1, setup_option=ic4.StreamSetupOption.ACQUISITION_START)

buffer = sink.snap_single(1000)
buffer.save_as_bmp("./images/L_" + str(1) + ".png")
buffer1 = sink1.snap_single(1000)
buffer1.save_as_bmp("./images/R_" + str(1) + ".png")
```

But it didn‘t save image and show this:
```
Traceback (most recent call last):
  File "E:\Project\Xeryon_motor_control\ploy_fit.py", line 63, in <module>
    buffer = sink.snap_single(1000)
  File "E:\Anaconda\envs\py38\lib\site-packages\imagingcontrol4\snapsink.py", line 164, in snap_single
    IC4Exception.raise_exception_from_last_error()
  File "E:\Anaconda\envs\py38\lib\site-packages\imagingcontrol4\ic4exception.py", line 46, in raise_exception_from_last_error
    raise IC4Exception(err, message.value.decode("utf-8"))
imagingcontrol4.ic4exception.IC4Exception: (<ErrorCode.Timeout: 27>, 'ic4_snapsink_snap_single: Timeout elapsed')
```

Can you give me some recommendations, thank you.

**Comment by TIS-Tim** [comment]
Are you sure that TriggerMode is Off for both devices?

**Comment by Skullface9512** [comment]
Sorry i'm not set TriggerMode and i set TriggerMode like that:
```
grabber.device_property_map.set_value(ic4.PropId.TRIGGER_MODE,"Off")
grabber1.device_property_map.set_value(ic4.PropId.TRIGGER_MODE,"Off")
```
the running result has no change, is there any problems.

**Comment by TIS-Tim** [comment]
If your cameras are connected to USB3, you could also increase the frame rate to make everything go faster.

**Comment by Skullface9512** [comment]
Hi Tim，I tried to show capture video through opencv, the mothod is:
```
import imagingcontrol4 as ic4
import cv2
def example_imagebuffer_numpy_opencv_snap():
    device_list = ic4.DeviceEnum.devices()
    for i, dev in enumerate(device_list):
        print(f"[{i}] {dev.model_name} ({dev.serial}) [{dev.interface.display_name}]")
    print(f"Select device [0..{len(device_list) - 1}]: ", end="")
    selected_index = int(input())
    dev_info = device_list[selected_index]

    grabber = ic4.Grabber()
    grabber.device_open(dev_info)

    cv2.namedWindow("display")

    sink = ic4.SnapSink()
    # sink = ic4.QueueSink(accepted_pixel_formats=ic4.native.IC4_PIXEL_FORMAT.IC4_PIXEL_FORMAT_BayerGB8,max_output_buffers=1,listener=QueueSinkListener)
    grabber.stream_setup(sink)

    while True:

        buffer = sink.snap_single(1000)
        np = buffer.numpy_wrap()
        np_1=cv2.resize(np,(np.shape[1]//3,np.shape[0]//3), interpolation=cv2.INTER_LINEAR)
        cv2.imshow("display", np_1)
        cv2.waitKey(1)

    grabber.stream_stop()


if __name__ == "__main__":
    ic4.Library.init(api_log_level=ic4.LogLevel.INFO, log_targets=ic4.LogTarget.STDERR)

    try:
        example_imagebuffer_numpy_opencv_snap()
    finally:
        ic4.Library.exit()

```

but video is grayscale, can i set it as RGB video and how can i increase its frame rate, the device i used is DFM 37UX178-ML.

**Comment by TIS-Tim** [comment]
If you create your sink with an `accepted_pixel_formats` parameter, you can force an automatic buffer format conversion to RGB:

    sink = ic4.SnapSink(accepted_pixel_formats=[ic4.PixelFormat.BGR8])

`buffer` will then contain RGB data (3 bytes per pixel; you may or may not have to adjust your OpenCV to match that.

**Comment by Skullface9512** [comment]
Hi Tim, today i tried to capture video, but come across a problem:
```
Traceback (most recent call last):
  File "E:\Project\ic4-examples-master\python\imagebuffer-numpy-opencv-snap.py", line 119, in <module>
    example_imagebuffer_numpy_opencv_snap()
  File "E:\Project\ic4-examples-master\python\imagebuffer-numpy-opencv-snap.py", line 72, in example_imagebuffer_numpy_opencv_snap
    buffer = sink.snap_single(5000)
  File "E:\Anaconda\envs\py38\lib\site-packages\imagingcontrol4\snapsink.py", line 164, in snap_single
    IC4Exception.raise_exception_from_last_error()
  File "E:\Anaconda\envs\py38\lib\site-packages\imagingcontrol4\ic4exception.py", line 46, in raise_exception_from_last_error
    raise IC4Exception(err, message.value.decode("utf-8"))
imagingcontrol4.ic4exception.IC4Exception: (<ErrorCode.Timeout: 27>, 'ic4_snapsink_snap_single: Timeout elapsed')
```

Then i tried "buffer = sink.snap_single(1000)" as "buffer = sink.snap_single(5000)", but the result has no changes, can you give me some recommendation.

**Comment by Skullface9512** [comment]
Hi Tim, today i tried to capture video, but come across a problem:
```
Traceback (most recent call last):
  File "E:\Project\ic4-examples-master\python\imagebuffer-numpy-opencv-snap.py", line 119, in <module>
    example_imagebuffer_numpy_opencv_snap()
  File "E:\Project\ic4-examples-master\python\imagebuffer-numpy-opencv-snap.py", line 72, in example_imagebuffer_numpy_opencv_snap
    buffer = sink.snap_single(1000)
  File "E:\Anaconda\envs\py38\lib\site-packages\imagingcontrol4\snapsink.py", line 164, in snap_single
    IC4Exception.raise_exception_from_last_error()
  File "E:\Anaconda\envs\py38\lib\site-packages\imagingcontrol4\ic4exception.py", line 46, in raise_exception_from_last_error
    raise IC4Exception(err, message.value.decode("utf-8"))
imagingcontrol4.ic4exception.IC4Exception: (<ErrorCode.Timeout: 27>, 'ic4_snapsink_snap_single: Timeout elapsed')
```

Then i tried "buffer = sink.snap_single(1000)" as "buffer = sink.snap_single(5000)", but the result has no changes, can you give me some recommendation.

**Comment by TIS-Tim** [comment]
Are you sure TriggerMode is still Off (for every TriggerSelector)?
What happens if you reconnect the camera?

**Comment by KalpitBakal** [comment]
> The qt6-first-steps example shows how to display live video: https://github.com/TheImagingSource/ic4-examples/tree/master/python/qt6/qt6-first-steps

Hello! I tried working with this but I am getting an error ' _module 'imagingcontrol4.pyside6' has no attribute 'DeviceSelectionDialog'_ 

I am new in the application programming interface so I would appreciate all the help I can get to get started. As I explained before, I would like to first start with a live video in a window. Then start saving a video after I click a button or after a certain duration.

**Comment by TIS-Tim** [comment]
Did you install all required dependencies? Probably imagingcontrol4pyside6 is missing.

`pip install -r requirements.txt`

**Comment by KalpitBakal** [comment]
![Image](https://github.com/user-attachments/assets/01849aad-f1f3-4b4e-9cc7-293368881219)

I followed these steps to install both imagingcontrol4 and imagingcontrol4pyside6. (https://www.theimagingsource.com/en-us/documentation/ic4python/guide-getting-started.html) using Anaconda Prompt. 

I am using Visual Studio Code for writing my code. Please let me know if you need more information.

**Comment by KalpitBakal** [comment]
> import imagingcontrol4pyside6
print(dir(imagingcontrol4pyside6))

This gives _ImportError: DLL load failed while importing imagingcontrol4pyside6lib: The specified procedure could not be found._

Output of `pip list` in Anaconda prompt shows both _imagingcontrol4 version1.1.0.2833rc0_ and _imagingcontrol4pyside6 version        6.7.0.51_

Please let me know what should I do next.

**Comment by TIS-Tim** [comment]
Ah, your version of imagingcontrol4 is old. 1.1.0.2833rc0 is not the current version (and you probably shouldn't be using rc builds).

The most recent version is 1.2.0.2954:

https://pypi.org/project/imagingcontrol4/#history

I think using the correct version your problem should go away.

**Comment by KalpitBakal** [comment]
I have updated both. Now the pip list command gives: 
_imagingcontrol4 version 1.2.0.2954
imagingcontrolpyside6 version 6.7.0.51_

But running ```
import imagingcontrol4pyside6
print(dir(imagingcontrol4pyside6))
```
still gives the error _DLL load failed while importing imagingcontrol4pyside6lib: The specified procedure could not be found._


I had tried this with the recent version earlier, since I got the error I changed it to an older version (probably should not have done that in hindsight). 

Just fyi, I did not use virtual environments to separate library installations. 

Please let me know if you need more information.

**Comment by TIS-Tim** [comment]
Which Python version do you use?

**Comment by KalpitBakal** [comment]
Currently, _python 3.9.7_. Updating it to the newest version now.

**Comment by KalpitBakal** [comment]
I have updated my Python version. When I try to do `python -m pip install imagingcontrol4pyside6` from my command prompt as an admin. I ge this error: 

_INFO: pip is looking at multiple versions of imagingcontrol4pyside6 to determine which version is compatible with other requirements. This could take a while.
  Using cached imagingcontrol4pyside6-6.6.0.51-py38-none-win_amd64.whl.metadata (5.2 kB)
ERROR: Cannot install imagingcontrol4pyside6==6.6.0.51 and imagingcontrol4pyside6==6.7.0.51 because these package versions have conflicting dependencies.

The conflict is caused by:
    imagingcontrol4pyside6 6.7.0.51 depends on pyside6<6.8 and >=6.7.2
    imagingcontrol4pyside6 6.6.0.51 depends on pyside6<6.7 and >=6.6.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts_

**Comment by TIS-Tim** [comment]
You cannot install both versions at the same time.

I also don't see what exactly is the conflict between those dependencies.

Do you have PySide6=6.8.x installed? You will need to downgrade that to 6.7.x.

**Comment by KalpitBakal** [comment]
When I try to import PySide6 in python it gives me the error: _No module named 'PySide6'_. 
So it means I do not have it installed. 

I am kind of confused what is happening now.

**Comment by TIS-Tim** [comment]
I have no knowledge of how anaconda works.

When just using pip, it does not matter whether you use a venv or not; but on some systems installing globally is restricted.

That message sounds like your pip only has access to the newer versions of PySide6 -- you will have to wait for us to rebuild the bindings for the newer version (or figure out a way to install the old).

**Comment by KalpitBakal** [comment]
I have removed anaconda now. I am using Python(the recent version) only. On PyPi I can only see the 6.8 versions of PySide6. I will try to get the old version using git or something else (still figuring that out as I am kind of new to this.)

How much time will it take to rebuild the bindings for the newer version? 

Maybe what can help me being faster is if we can get on a TEAMS/zoom call to see what is wrong with my setup? Do you think it is a good idea?

**Comment by TIS-Tim** [comment]
Just created a throw-away venv right now, everything works as it should

```
P:\>python -m venv newenv

P:\>cd newenv

P:\newenv>Scripts\activate.bat

(newenv) P:\newenv>where python
P:\newenv\Scripts\python.exe
C:\Users\Tim\AppData\Local\Microsoft\WindowsApps\python.exe

(newenv) P:\newenv>python -m pip install imagingcontrol4
Collecting imagingcontrol4
  Using cached imagingcontrol4-1.2.0.2954-py38-none-win_amd64.whl.metadata (5.4 kB)
Using cached imagingcontrol4-1.2.0.2954-py38-none-win_amd64.whl (11.5 MB)
Installing collected packages: imagingcontrol4
Successfully installed imagingcontrol4-1.2.0.2954

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(newenv) P:\newenv>python -m pip install imagingcontrol4pyside6
Collecting imagingcontrol4pyside6
  Using cached imagingcontrol4pyside6-6.7.0.51-py38-none-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: imagingcontrol4>=1.0.0 in p:\newenv\lib\site-packages (from imagingcontrol4pyside6) (1.2.0.2954)
Collecting pyside6<6.8,>=6.7.2 (from imagingcontrol4pyside6)
  Using cached PySide6-6.7.3-cp39-abi3-win_amd64.whl.metadata (5.5 kB)
Collecting shiboken6==6.7.3 (from pyside6<6.8,>=6.7.2->imagingcontrol4pyside6)
  Using cached shiboken6-6.7.3-cp39-abi3-win_amd64.whl.metadata (2.6 kB)
Collecting PySide6-Essentials==6.7.3 (from pyside6<6.8,>=6.7.2->imagingcontrol4pyside6)
  Using cached PySide6_Essentials-6.7.3-cp39-abi3-win_amd64.whl.metadata (3.8 kB)
Collecting PySide6-Addons==6.7.3 (from pyside6<6.8,>=6.7.2->imagingcontrol4pyside6)
  Using cached PySide6_Addons-6.7.3-cp39-abi3-win_amd64.whl.metadata (4.1 kB)
Using cached imagingcontrol4pyside6-6.7.0.51-py38-none-win_amd64.whl (182 kB)
Using cached PySide6-6.7.3-cp39-abi3-win_amd64.whl (539 kB)
Using cached PySide6_Addons-6.7.3-cp39-abi3-win_amd64.whl (123.6 MB)
Using cached PySide6_Essentials-6.7.3-cp39-abi3-win_amd64.whl (68.9 MB)
Using cached shiboken6-6.7.3-cp39-abi3-win_amd64.whl (1.1 MB)
Installing collected packages: shiboken6, PySide6-Essentials, PySide6-Addons, pyside6, imagingcontrol4pyside6
Successfully installed PySide6-Addons-6.7.3 PySide6-Essentials-6.7.3 imagingcontrol4pyside6-6.7.0.51 pyside6-6.7.3 shiboken6-6.7.3

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(newenv) P:\newenv>python -m pip list
Package                Version
---------------------- ----------
imagingcontrol4        1.2.0.2954
imagingcontrol4pyside6 6.7.0.51
pip                    24.3.1
PySide6                6.7.3
PySide6_Addons         6.7.3
PySide6_Essentials     6.7.3
shiboken6              6.7.3

(newenv) P:\newenv>python
Python 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import imagingcontrol4
>>> dir(imagingcontrol4.pyside6)
['DeviceSelectionDialog', 'DisplayWidget', 'DisplayWindow', 'PropertyDialog', 'QApplication', '_HAS_PYSIDE6', '__all_pyside6', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'display']
>>>
```

I don't even have to tell it to get a specific version, it automagically selects PySide6=6.7.x.

**Comment by TIS-Tim** [comment]
I just installed 3.13; looks like PySide6==6.7 is not available for Python3.13.

I think downgrading is a good idea for now.

**Comment by KalpitBakal** [comment]
This worked now! Phew. Now the actual work starts. I will close this thread now and start a new thread with specific questions. Thank you Tim for all your help and quick responses.

**Comment by TIS-Tim** [comment]
@KalpitBakal 

There are now a preview release of imagingcontrol4pyside6 available (install with pip install --pre) that works with PySide6==6.8.
